name: Deploy to Server

on:
  workflow_run:
    workflows: ["Docker Build and Push to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploiement Ansible
        uses: dawidd6/action-ansible-playbook@v2
        env:
          GHCR_TOKEN: ${{ secrets.GH_TOKEN }}
          GHCR_USER: ${{ github.actor }}
        with:
          playbook: ansible_playbook.yml
          inventory: |
            [servers]
            ${{ secrets.HOST }} ansible_user=${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}